on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      shell: cmd
      run: clang -fuse-ld=lld -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS capture.cxx conv.cxx wave.cxx program.cxx -lole32
    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        path: a.exe
        if-no-files-found: error
